# Generated by Django 5.1.7 on 2025-04-05 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
    ]
