# Generated by Django 5.1.7 on 2025-04-09 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='total_price',
        ),
    ]
