# Generated by Django 5.1.7 on 2025-04-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_cartitem_total_price_wishlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
