# Generated by Django 5.1.7 on 2025-03-27 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('p', 'Pizza'), ('s', 'Sides'), ('d', 'Desserts'), ('dr', 'Drinks')], max_length=100, unique=True),
        ),
    ]
