# Generated by Django 5.1.7 on 2025-03-27 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_remove_category_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToppingsCustomization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='food_images/'),
        ),
        migrations.AddField(
            model_name='food',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='food',
            name='price',
            field=models.DecimalField(decimal_places=2, blank=True, null=True, max_digits=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='FoodTopping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toppings', to='category.food')),
                ('topping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.toppingscustomization')),
            ],
        ),
    ]
